# Title -------------------------------------------------------------------

#  Data import and cleaning for MSP


# Packages ----------------------------------------------------------------

library(readr)
library(stringr)


# Functions ---------------------------------------------------------------

# Function replacing Yes and No variables as 1s and 0s
yes_one_no_zero <- function(x){
  x[x=="N"] <- 0
  x[x=="No"] <- 0
  x[x=="Y"] <- 1
  x[x=="Yes"] <- 1
  as.logical(as.numeric(x))
}

# Function to replace NAs with 0s
nas_to_zeros <- function(y){
  y[is.na(y)] <- 0
}


# Import student profile data ---------------------------------------------

# Import student data and define data type for each column
students <- read_csv("one_student_one_row_de_identified_3.csv", 
                     na = c("", "NA","–","‡","†","NULL"),
                     col_types = cols(
                       hashed_puid = col_character(),
                       hashed_person_uid = col_character(),
                       academic_school_grouping_desc = col_character(),
                       department_short_title = col_character(),
                       profile_academic_period = col_integer(),
                       profile_academic_period_desc = col_character(),
                       profile_admissions_population = col_character(),
                       profile_admissions_pop_desc = col_character(),
                       profile_college = col_character(),
                       profile_firstime_fulltime_ind = col_character(),
                       profile_gender_desc = col_character(),
                       profile_highest_sat_math = col_double(),
                       profile_highest_sat_writing = col_double(),
                       profile_highest_sat_crit_read = col_double(),
                       profile_highest_act_english = col_double(),
                       profile_highest_act_math = col_double(),
                       profile_highest_act_reading = col_double(),
                       profile_highest_act_sci_reason = col_double(),
                       profile_highest_act_composite = col_double(),
                       profile_highest_act_englwrit = col_double(),
                       profile_major = col_character(),
                       profile_reporting_campus = col_character(),
                       profile_reporting_ethnicity = col_character(),
                       profile_residence_desc = col_character(),
                       profile_sat_total = col_double(),
                       profile_underrep_minority_ind = col_character(),
                       one_year_retention_flag = col_logical(),
                       two_year_retention_flag = col_logical(),
                       three_year_retention_flag = col_logical(),
                       three_year_graduation_flag = col_logical(),
                       four_year_graduation_flag = col_logical(),
                       five_year_graduation_flag = col_logical(),
                       six_year_graduation_flag = col_logical(),
                       graduated_flag = col_logical(),
                       associate_1_grad = col_integer(),
                       associate_1_overall_gpa = col_double(),
                       associate_1_overall_credits_earned = col_double(),
                       bach_1_grad = col_integer(),
                       bach_1_overall_gpa = col_double(),
                       bach_1_overall_credits_earned = col_double(),
                       #grad_1_fed_loan_amount_not_parent = col_double(),
                       #grad_1_fed_parent_loan_amount = col_double(),
                       #grad_1_degree_1_type = col_character(),
                       #grad_1_degree_1_college = col_character(),
                       #grad_1_degree_1_major = col_character(),
                       #grad_1_degree_2_type = col_character(),
                       #grad_1_degree_2_college = col_character(),
                       #grad_1_degree_2_major = col_character(),
                       #grad_1_degree_3_type = col_character(),
                       #grad_1_degree_3_college = col_character(),
                       #grad_1_degree_3_major = col_character(),
                       #grad_1_degree_4_type = col_character(),
                       #grad_1_degree_4_college = col_character(),
                       #grad_1_degree_4_major = col_character(),
                       #grad_1_degree_5_type = col_character(),
                       #grad_1_degree_5_college = col_character(),
                       #grad_1_degree_5_major = col_character(),
                       bach_2_grad = col_integer(),
                       bach_2_overall_gpa = col_double(),
                       bach_2_overall_credits_earned = col_double(),
                       #grad_2_fed_loan_amount_not_parent = col_double(),
                       #grad_2_fed_parent_loan_amount = col_double(),
                       #grad_2_degree_1_type = col_character(),
                       #grad_2_degree_1_college = col_character(),
                       #grad_2_degree_1_major = col_character(),
                       #grad_2_degree_2_type = col_character(),
                       #grad_2_degree_2_college = col_character(),
                       #grad_2_degree_2_major = col_character(),
                       #grad_2_degree_3_type = col_character(),
                       #grad_2_degree_3_college = col_character(),
                       #grad_2_degree_3_major = col_character(),
                       bach_3_grad = col_integer(),
                       bach_3_overall_gpa = col_double(),
                       bach_3_overall_credits_earned = col_double(),
                       #grad_3_fed_loan_amount_not_parent = col_double(),
                       #grad_3_fed_parent_loan_amount = col_double(),
                       #grad_3_degree_1_type = col_character(),
                       #grad_3_degree_1_college = col_character(),
                       #grad_3_degree_1_major = col_character(),
                       #pell_efc = col_double(),
                       percent_semesters_with_payment_plan = col_double(),
                       county_desc = col_character(),
                       nation_of_citizenship_desc = col_character(),
                       athlete_flag = col_logical(),
                       first_gen_flag = col_logical(),
                       first_year_first_gen_flag = col_logical(),
                       bgr = col_logical(),
                       bgri = col_logical(),
                       bop_flag = col_logical(),
                       cco_internship_flag = col_logical(),
                       cco_internships = col_character(),
                       citizenship_desc = col_character(),
                       coop_flag = col_logical(),
                       drc_flag = col_logical(),
                       early_start_flag = col_logical(),
                       geare_flag = col_logical(),
                       hs_location_zip = col_integer(),
                       hs_school_name = col_character(),
                       hs_title_i_school_status = col_character(),
                       hs_urban_centric_locale = col_character(),
                       horizons_flag = col_logical(),
                       incoming_credits_flag = col_character(),
                       incoming_credits_distributed_credits = col_double(),
                       total_incoming_credits = col_double(),
                       incoming_credits_undistributed_credits = col_double(),
                       learning_communities_flag = col_logical(),
                       lgbtq_flag = col_double(),
                       mep_academic_boot_camp = col_logical(),
                       entr_flag = col_logical(),
                       summer_start_flag = col_logical(),
                       academic_bootcamp_flag = col_logical(),
                       probation_flag = col_logical(),
                       purdue_bound_flag = col_logical(),
                       purpromise_flag = col_logical(),
                       si_attended_flag = col_logical(),
                       si_count = col_double(),
                       si_student_leader_flag = col_logical(),
                       span_plan_nontraditional_student_flag = col_logical(),
                       study_abroad_flag = col_logical(),
                       scholarship_flag = col_logical(),
                       pres_scholar_flag = col_logical(),
                       beering_scholar_flag = col_logical(),
                       trustee_scholar_flag = col_logical(),
                       stamps_ldrs_scholar_flag = col_logical(),
                       emerging_ldr_flag = col_logical(),
                       summer_finish_flag = col_logical(),
                       summer_stay_flag = col_logical(),
                       student_of_concern_flag = col_logical(),
                       behavioral_intervention_flag = col_logical(),
                       expulsion_suspension_probation_warning_flag = col_logical(),
                       twenty_first_century_scholar_flag = col_logical(),
                       military_active_flag = col_logical(),
                       military_veteran_flag = col_logical(),
                       military_family_flag = col_logical(),
                       wiepgroup_mentoring_flag = col_logical(),
                       wieppair_mentoring_flag = col_logical(),
                       reason_for_leaving = col_character(),
                       overall_gpa_when_leaving = col_double(),
                       one_year_overall_gpa = col_double(),
                       one_year_credits_attempted = col_double(),
                       one_year_credits_earned = col_double()))

# Replace Yes and No responses to 1s and 0s for first-time full-time and URM students
students$profile_firstime_fulltime_ind <- yes_one_no_zero(students$profile_firstime_fulltime_ind)
students$profile_underrep_minority_ind <- yes_one_no_zero(students$profile_underrep_minority_ind)

# Change gender data type to factor and create a new column with gender as 0s for female and 1s for male
students$profile_gender_desc <- as.factor(students$profile_gender_desc)
students$profile_gender[students$profile_gender_desc=="Female"] <- 0
students$profile_gender[students$profile_gender_desc=="Male"] <- 1
students$profile_gender <- as.logical(as.numeric(students$profile_gender))

# Replace NAs with 0s for relevant variables (semesters on payment plan, incoming credits, MEP bootcamp, SI count)
students$percent_semesters_with_payment_plan <- nas_to_zeros(students$percent_semesters_with_payment_plan)
students$incoming_credits_flag <- nas_to_zeros(students$incoming_credits_flag)
students$mep_academic_boot_camp <- nas_to_zeros(students$mep_academic_boot_camp)
students$si_count <- nas_to_zeros(students$si_count)

# Split academic period description into a column for term (Fall or Spring) and year
term <- str_split_fixed(students$profile_academic_period_desc, " ", 2)
colnames(term) <- c("Term","Year")
students <- cbind(students, term)

# Create column "transfer" for transfer student indicator
students$transfer <- FALSE
students$transfer <- replace(students$transfer, students$profile_admissions_population == "T" | students$profile_admissions_population == "ST", TRUE)

# Create column "URM" for non-White, non-Asian, and non-international student indicator
students$URM <- TRUE
students$URM <- replace(students$URM, students$profile_reporting_ethnicity == "White" | 
                          students$profile_reporting_ethnicity == "Asian" | 
                          students$profile_reporting_ethnicity == "International" |
                          students$profile_reporting_ethnicity == "Unknown" |
                          students$profile_reporting_ethnicity == "2 or more races", 
                        FALSE)

# Create variables for support programs
# Variables for orientation - bgr, bgri, bop_flag
# Variables for minoritized students - bop_flag, mep_academic_boot_camp, horizons_flag, wiepgroup_mentoring_flag, wieppair_mentoring_flag
# Variables for at-risk students - drc_flag, student_of_concern_flag
# Other variables - learning_communities_flag, percent_semesters_with_payment_plan, cco_internship_flag, coop_flag, si_attended_flag, study_abroad_flag

# Import semester data ----------------------------------------------------

# Import semester data and define data type for each column
# Dates have varying formats within the same column so they are imported as character strings
semesters <- read_csv("grades_join_with_all_de_identified.csv",
                      na = c("", "NA","–","‡","†"),
                      col_types = cols(
                        academic_period = col_integer(),
                        academic_period_desc = col_character(),
                        semester = col_character(),
                        reporting_campus = col_character(),
                        reporting_campus_desc = col_character(),
                        campus = col_character(),
                        campus_desc = col_character(),
                        tsw_sites = col_character(),
                        id = col_character(),
                        person_uid = col_character(),
                        reporting_ethnicity = col_character(),
                        underrepresented_minority = col_character(),
                        underrepresented_minority_ind = col_character(),
                        gender_desc = col_character(),
                        student_residency_desc = col_character(),
                        student_level = col_character(),
                        student_level_desc = col_character(),
                        classification = col_character(),
                        program = col_character(),
                        college = col_character(),
                        college_desc = col_character(),
                        major = col_character(),
                        major_desc = col_character(),
                        first_concentration = col_character(),
                        first_concentration_desc = col_character(),
                        reporting_campus_credits = col_double(),
                        current_age = col_double(),
                        age_range = col_character(),
                        county = col_character(),
                        county_desc = col_character(),
                        nation_of_citizenship_desc = col_character(),
                        state_province = col_character(),
                        citizenship_type = col_character(),
                        county_apa = col_character(),
                        state_province_apa = col_character(),
                        nation_of_citizenship_apa = col_character(),
                        full_time_part_time = col_character(),
                        fte = col_double(),
                        degree = col_character(),
                        teacher_ind = col_character(),
                        department = col_integer(),
                        academic_school_grouping = col_character(),
                        academic_school_grouping_desc = col_character(),
                        freeze_event = col_character(),
                        department_short_title = col_character(),
                        first_gen_puid = col_character(),
                        course_identification = col_character(),
                        final_grade = col_character(),
                        subject_desc = col_character(),
                        course_number = col_integer(),
                        course_credits = col_double(),
                        course_college = col_character(),
                        course_department = col_character(),
                        repeat_course_ind = col_character(),
                        schedule_type = col_character(),
                        transfer_course_ind = col_character(),
                        overall_gpa = col_double(),
                        overall_credits_earned = col_double(),
                        term_gpa = col_double(),
                        term_credits_earned = col_double(),
                        first_gen = col_logical(),
                        acad_standing_beg_desc = col_character(),
                        acad_standing_end_desc = col_character(),
                        athlete_flag = col_logical(),
                        sport_list = col_character(),
                        sport_list_desc = col_character(),
                        bgr = col_logical(),
                        bgr_year = col_integer(),
                        bgri = col_logical(),
                        bgrleader_flag = col_logical(),
                        bgr_leader_position = col_character(),
                        bgr_leader_year = col_integer(),
                        bop_flag = col_logical(),
                        bop_campus = col_character(),
                        bop_course_identification = col_character(),
                        bop_course_reference_number = col_integer(),
                        bop_course_section_number = col_character(),
                        bop_course_title = col_character(),
                        bop_id = col_integer(),
                        cco_continuing_ed_school = col_character(),
                        cco_employer = col_character(),
                        cco_internship = col_character(),
                        cco_internflag = col_character(),
                        cco_location = col_character(),
                        cco_plan = col_character(),
                        cco_salary = col_double(),
                        coop_flag = col_logical(),
                        coop_division = col_character(),
                        coop_employer = col_character(),
                        coop_program = col_character(),
                        coop_session_academic_period = col_integer(),
                        coop_session_date = col_character(),
                        coop_status = col_character(),
                        cos_program = col_character(),
                        drc_flag = col_logical(),
                        frat_sorority_flag = col_logical(),
                        frat_sorority_chapter = col_character(),
                        frat_sorority_type = col_character(),
                        early_start_flag = col_logical(),
                        early_start = col_character(),
                        first_gen_flag = col_logical(),
                        geare_flag = col_logical(),
                        geare_employer = col_character(),
                        geare_internship_type = col_character(),
                        geare_location = col_character(),
                        geare_status = col_character(),
                        hs_agency_id_nces_assigned = col_integer(),
                        hs_agency_name = col_character(),
                        hs_ai_code = col_integer(),
                        hs_american_indian_alaska_native_female = col_double(),
                        hs_american_indian_alaska_native_gender_unknown = col_double(),
                        hs_american_indian_alaska_native_male = col_double(),
                        hs_american_indian_alaska_native_students = col_double(),
                        hs_asian_or_asian_pacific_islander_female = col_double(),
                        hs_asian_or_asian_pacific_islander_male = col_double(),
                        hs_asian_or_asian_pacific_islander_students = col_double(),
                        hs_asian_pacific_islander_gender_unknown = col_double(),
                        hs_black_female = col_double(),
                        hs_black_gender_unknown = col_double(),
                        hs_black_male = col_double(),
                        hs_black_students = col_double(),
                        hs_charter_school = col_character(),
                        hs_county_name = col_character(),
                        hs_direct_certification = col_double(),
                        hs_female_students = col_double(),
                        hs_free_and_reduced_lunch_students = col_double(),
                        hs_free_lunch_eligible = col_double(),
                        hs_full_time_equivalent_fte_teachers = col_double(),
                        hs_gender_unknown_students = col_double(),
                        hs_hawaiian_nat_pacific_isl_female = col_double(),
                        hs_hawaiian_nat_pacific_isl_male = col_double(),
                        hs_hawaiian_nat_pacific_isl_students = col_double(),
                        hs_highest_grade_offered = col_character(),
                        hs_hispanic_female = col_double(),
                        hs_hispanic_gender_unknown = col_double(),
                        hs_hispanic_male = col_double(),
                        hs_hispanic_students = col_double(),
                        hs_locale = col_character(),
                        hs_location_zip4 = col_integer(),
                        hs_location_zip = col_integer(),
                        hs_lowest_grade_offered = col_character(),
                        hs_magnet_school = col_character(), #binary (1-Yes, 2-No)
                        hs_male_students = col_double(),
                        hs_migrant_students = col_double(),
                        hs_out_of_state_flag = col_character(), #binary (2-No)
                        hs_pupil_teacher_ratio = col_double(),
                        hs_reduced_price_lunch_eligible_students = col_double(),
                        hs_school_id_nces_assigned = col_character(),
                        hs_school_level_code = col_character(),
                        hs_school_name = col_character(),
                        hs_school_name_latest_available = col_character(),
                        hs_school_type = col_character(),
                        hs_school_wide_title_i = col_character(), #binary (1-Yes, 2-No)
                        hs_shared_time_school = col_character(), #binary (1-Yes, 2-No)
                        hs_state_abbr = col_character(),
                        hs_state_name = col_character(),
                        hs_title_i_eligible_school = col_character(), #binary (1-Yes, 2-No)
                        hs_title_i_school_status = col_character(),
                        hs_total_students_all_grades_excludes_ae = col_double(),
                        hs_two_or_more_races_female = col_double(),
                        hs_two_or_more_races_male = col_double(),
                        hs_two_or_more_races_students = col_double(),
                        hs_urban_centric_locale = col_character(),
                        hs_virtual_school_status = col_character(), #binary (A virtual school, Not a virtual school)
                        hs_white_female = col_double(),
                        hs_white_gender_unknown = col_double(),
                        hs_white_male = col_double(),
                        hs_white_students = col_double(),
                        horizons_flag = col_logical(),
                        horizons_cohort = col_integer(),
                        housing_application_type = col_character(),
                        housing_resident_hall = col_character(),
                        housing_move_in_date = col_character(), # date formats are inconsistent
                        housing_move_out_date = col_character(), # date formats are inconsistent
                        incoming_credits_ap_credits = col_double(),
                        incoming_credits_distributed_credits = col_double(),
                        incoming_credits_dual_credits = col_double(),
                        incoming_credits_flag = col_character(),
                        incoming_credits_ib_credits = col_double(),
                        total_incoming_credits = col_double(),
                        incoming_credits_undistributed_credits = col_double(),
                        learning_communities_flag = col_logical(),
                        learning_communities_code = col_character(),
                        learning_communities_description = col_character(),
                        learning_communities_reside = col_character(),
                        lgbtq_flag = col_double(),
                        mep_flag = col_logical(),
                        mep_sew_6 = col_logical(),
                        mep_sew_7 = col_logical(),
                        mep_sew_8 = col_logical(),
                        mep_preface_9 = col_logical(),
                        mep_preface_10 = col_logical(),
                        mep_mite = col_logical(),
                        mep_promise = col_logical(),
                        mep_preview = col_logical(),
                        mep_academic_boot_camp = col_logical(),
                        mep_abc_gpa = col_double(),
                        mep_e180 = col_logical(),
                        mep_ret_program_status = col_character(),
                        mep_first_sem_high_tut_center_use = col_logical(),
                        entr_flag = col_logical(),
                        entr_acad_period_grad = col_integer(),
                        entr_acad_period_grad_desc = col_character(),
                        entr_status_desc = col_character(),
                        entr_degree = col_character(),
                        entr_major = col_character(),
                        summer_start_flag = col_logical(),
                        summer_start_conditional_flag = col_logical(),
                        summer_start_unconditional_flag = col_logical(),
                        academic_bootcamp_flag = col_logical(),
                        academic_bootcamp_semester = col_character(),
                        probation_flag = col_logical(),
                        probation_category = col_character(),
                        probation_answer = col_character(),
                        probation_how_much = col_character(),
                        probation_last_time_updated = col_character(), # date formats are inconsistent
                        purdue_bound_flag = col_logical(),
                        purpromise_flag = col_logical(),
                        purpromise_cohort = col_integer(),
                        si_attended_flag = col_logical(),
                        si_count = col_double(),
                        si_course = col_character(),
                        si_student_leader_flag = col_logical(),
                        span_plan_nontraditional_student_flag = col_logical(),
                        star_flag = col_logical(),
                        star_schedule_number = col_character(),
                        star_date = col_character(), # date formats are inconsistent
                        star_type = col_character(),
                        star_status = col_character(),
                        star_year = col_integer(),
                        star_program_leader_flag = col_logical(),
                        star_program_leader_year = col_integer(),
                        study_abroad_flag = col_logical(),
                        study_abroad_country_name = col_character(),
                        study_abroad_duration_days = col_double(),
                        study_abroad_end_date = col_character(), # date formats are inconsistent
                        study_abroad_program_name = col_character(),
                        study_abroad_start_date = col_character(), # date formats are inconsistent
                        study_abroad_program_type = col_character(),
                        study_abroad_term = col_character(),
                        scholarship_flag = col_logical(),
                        scholarship_cohort = col_character(),
                        scholarship_cohort_desc = col_character(),
                        scholarship = col_character(),
                        pres_scholar_flag = col_logical(),
                        beering_scholar_flag = col_logical(),
                        trustee_scholar_flag = col_logical(),
                        stamps_ldrs_scholar_flag = col_logical(),
                        emerging_ldr_flag = col_logical(),
                        summer_finish_flag = col_logical(),
                        summer_finish_term = col_character(),
                        summer_stay_flag = col_logical(),
                        summer_stay_term = col_character(),
                        osrr_flag = col_logical(),
                        ossr_type = col_character(),
                        ossr_case_created = col_character(), # date formats are inconsistent
                        ossr_charge_1 = col_character(),
                        ossr_finding_1 = col_character(),
                        ossr_charge_2 = col_character(),
                        ossr_finding_2 = col_character(),
                        ossr_charge_3 = col_character(),
                        ossr_finding_3 = col_character(),
                        ossr_charge_4 = col_character(),
                        ossr_finding_4 = col_character(),
                        ossr_charge_5 = col_character(),
                        ossr_finding_5 = col_character(),
                        ossr_charge_6 = col_character(),
                        ossr_finding_6 = col_character(),
                        ossr_classification = col_character(),
                        ossr_disciplinary_probation = col_character(),
                        ossr_expulsion = col_character(),
                        ossr_file_id = col_integer(),
                        ossr_probated_suspension = col_character(),
                        ossr_suspension = col_character(),
                        ossr_warning = col_character(),
                        twenty_first_century_scholar_flag = col_logical(),
                        vet_military_flag = col_logical(),
                        vet_military_campus = col_character(),
                        vet_military_student_level = col_character(),
                        vet_military_type = col_character(),
                        wiepgroup_mentoring_flag = col_logical(),
                        wiep_group_mentoring_academic_year = col_character(),
                        wiep_group_mentoring_attendance_possible = col_double(),
                        wiep_group_mentoring_attendance_total = col_double(),
                        wiep_group_mentoring_total_meetings = col_double(),
                        wiep_group_mentoring_total_social = col_double(),
                        wieppair_mentoring_flag = col_logical(),
                        wiep_pair_mentoring_academic_year = col_character(),
                        wiep_pair_mentoring_mentor_mentee = col_character(),
                        wiep_pair_mentoring_attendance_possible = col_double(),
                        wiep_pair_mentoring_attendance_total = col_double(),
                        wiep_pair_mentoring_total_meetings = col_double(),
                        wiep_pair_mentoring_total_socials = col_double()
                      ))

# semesters <- semesters %>% 
#   select(-semester,-reporting_campus,-campus,-campus_desc,tsw_sites,-person_uid,-underrepresented_minority,
#          -student_level,-first_concentration,-county_apa,-state_province_apa,-nation_of_citizenship_apa,-athlete_flag,
#          -sport_list,-sport_list_desc,-lgbtq_flag,-vet_military_flag,-vet_military_campus,-vet_military_student_level,
#          -vet_military_type)